apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      containers:
        -
          env:
            -
              name: NODE_ENV
              value: prod
            -
              name: dc
              value: sdc
          image: quay.io/weaveworks/helloworld:master-a000001
          imagePullPolicy: Always
          name: hello
          ports:
            - name: web
              containerPort: 9000
